site_name: Software Solutions
site_url: https://github.com/danieldreke/software-solutions/
repo_url: https://github.com/danieldreke/software-solutions/
copyright: I ❤️ Coding - Dan
extra_css:
  - assets/style.css
markdown_extensions:
  - pymdownx.magiclink  # Convert bare URLs into hyperlinks
  # - attr_list  # Allow setting attributes on block elements
  - admonition  # Add Bootstrap-styled alerts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  # - git-revision-date-localized
  # - git-authors
extra_javascript:
    - assets/script.js
extra:
  generator: false  # Hide "Made with Material for MkDocs"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danieldreke
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/danieldreke
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-dreke
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: https://cdn-icons-png.flaticon.com/128/16208/16208195.png
  favicon: https://cdn-icons-png.flaticon.com/128/16208/16208195.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.tabs  # Show tabs navigation on top bar
    - content.action.edit  # Show Edit Page
    - content.action.view  # Show View Source
    - navigation.top  # Show "Back to Top" on scrolling
    # - navigation.expand  # Expand left menu sections
    - navigation.footer  # Show footer navigation
    - content.code.copy
    - content.code.select
    # - content.code.prettify
  user_color_mode_toggle: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
